### ISSUE TITLE
Implement number of 'includes' 

### ISSUE THREAD

**Issue by pedrovclfaria** [ulisses/Static-Code-Analyzer#16]
Number of includes in a C file. Also, returns a list of those includes.

**Comment by ulisses** [comment]
In the Includes.hs file we have a public function that returns the list of SystemIncludes and a list of Includes.
By SystemIncludes we mean, includes that belong to C language ( p.e. #include <stdio.h> ) and by Includes we mean the include that a programmer uses to import his libraries ( i.e. #include "mylib.h" ).

Executing this function will return:

``` haskell
getIncludes :: FilePath -> IO ([SystemIncludes],[Includes])
```

Imagine that in you code file (main.c) you have:

``` c
  #include    <SYSstdio.h>
#include "stdioss.h"
 #include   <SYSstdio2.h>
#include "stdiossds.h"
. . . 
```

Executing this function will return:

``` haskell
getIncludes "main.c" => (["SYSstdio.h","SYSstdio2.h"],["stdioss.h","stdiossds.h"])
```
